- name: Install jenkins
  hosts: localhost
  vars:
    jenkins_hostname: localhost
   
  tasks:
    - name: Install git jenkins plugins
      jenkins_plugin: 
        name: git
        state: present
        with_dependencies: yes

    - name: Install ansible jenkins plugins
      jenkins_plugin: 
        name: ansible
        state: present
        with_dependencies: yes
    
    - name: Install terraform jenkins plugins
      jenkins_plugin: 
        name: terraform
        state: present
        with_dependencies: yes

    - name: Install blueocean jenkins plugins
      jenkins_plugin: 
        name: blueocean
        state: present
        with_dependencies: yes

  roles:
    - role: geerlingguy.jenkins
      become: yes
